services:
  postgres:
    image: postgres
    container_name: mediagrab-postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - "6443:6443"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: mediagrab-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  redis_data:

networks:
  backend:
    driver: bridge
