services:
  db:
    image: postgres
    container_name: multigrab-postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    ports:
      - "6443:6443"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: multigrab-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  db_data:
  redis_data:
  grafana_data:
  prometheus_data:

networks:
  backend:
    driver: bridge
