"""fixed tables

Revision ID: 8b76ddc5babf
Revises: 607a267fb39b
Create Date: 2024-08-19 17:00:18.558860

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b76ddc5babf"
down_revision: Union[str, None] = "607a267fb39b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("videos_user_fkey", "videos", type_="foreignkey")
    op.create_foreign_key(None, "videos", "users", ["user_id"], ["id"])
    op.drop_column("videos", "user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos", sa.Column("user", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.create_foreign_key("videos_user_fkey", "videos", "users", ["user"], ["id"])
    op.drop_column("videos", "user_id")
    # ### end Alembic commands ###
