"""Username not unique

Revision ID: b9599c3a62eb
Revises: 8415d561dce2
Create Date: 2024-07-10 13:53:15.337164

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9599c3a62eb"
down_revision: Union[str, None] = "8415d561dce2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
