"""fixed tables

Revision ID: ffdbeb4eb8e0
Revises: 8b76ddc5babf
Create Date: 2024-08-19 17:08:25.656861

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ffdbeb4eb8e0'
down_revision: Union[str, None] = '8b76ddc5babf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_user_id_fkey', 'videos', type_='foreignkey')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('videos_user_id_fkey', 'videos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
